products_details0 = [
    {'product_name': 'Laptop Gigabyte G6X 9KG 2024 i7-13650HX  / 16 GB / 1 TB / RTX 4060 / 165 Hz (9KG-43EE854SD)'},
    {'product_price': '4 299 zł'}, {
        'product_images': ['https://newsletter.morele.net/Gigabyte_Aorus_60EUR_Steam_1170x265_karta_produktu.png',
                           'https://images.morele.net/description/marketplace/7909c5aea9d0acd5b235c21341472c54.png',
                           'https://images.morele.net/description/marketplace/5c46fd6452ce9faefd48ae44b95c405d.png',
                           'https://images.morele.net/description/marketplace/da021fc9826ab2b142f0c384f3380c57.jpeg',
                           'https://images.morele.net/description/43/43c6477af49cfad400de25c44b2763eb.jpeg',
                           'https://images.morele.net/description/f3/f37e90c2ce9f7a608eeecacd271da1bb.jpeg',
                           'https://images.morele.net/description/marketplace/58592e862f7c2cf0d4278ce41d5d41d3.jpeg',
                           'https://images.morele.net/description/marketplace/d40b080926e6192344cd20f24eb82592.jpeg']},
     {'product_average_rate': '4/5'}, {'name': 'Producent', 'value': 'Gigabyte'},
    {'name': 'Kod producenta', 'value': '9KG-43EE854SD'}, {'name': 'EAN', 'value': '4719331758417'},
    {'name': 'Typ', 'value': 'Laptop'}, {'name': 'Zastosowanie', 'value': 'Gamingowe'},
    {'name': 'Kolor', 'value': 'Czarne'}, {'name': 'Seria', 'value': 'Gigabyte G6'},
    {'name': 'Rodzina procesora', 'value': 'Intel Core i7'}, {'name': 'Procesor', 'value': 'Intel Core i7-13650HX'},
    {'name': 'Taktowanie procesora (bazowe/turbo)', 'value': '1.9 GHz / 4.9 GHz'},
    {'name': 'Liczba rdzeni / wątków', 'value': '14/20'}, {'name': 'Pamięć RAM (zainstalowana)', 'value': '16 GB'},
    {'name': 'Pamięć RAM (maksymalna)', 'value': '64 GB'}, {'name': 'Typ pamięci RAM', 'value': 'DDR5'},
    {'name': 'Częstotliwość pamięci', 'value': '4800 MHz'},
    {'name': 'Ilość gniazd pamięci (ogółem/wolne)', 'value': '2/0'}, {'name': 'Dysk HDD', 'value': 'Brak'},
    {'name': 'Dysk SSD', 'value': 'Brak'}, {'name': 'Dysk SSD M.2', 'value': 'Brak'},
    {'name': 'Dysk SSD M.2 PCIe', 'value': '1 TB'}, {'name': 'Napędy', 'value': 'Brak'},
    {'name': 'Zintegrowany układ graficzny', 'value': 'Intel UHD Graphics Xe'},
    {'name': 'Dedykowany układ graficzny', 'value': 'NVIDIA GeForce RTX 4060 Laptop GPU'},
    {'name': 'Pamięć karty graficznej', 'value': '8 GB'}, {'name': 'Typ pamięci', 'value': 'GDDR6'},
    {'name': 'MGP', 'value': '105 W'}, {'name': 'Przekątna ekranu', 'value': '16"'},
    {'name': 'Rozdzielczość', 'value': '1920 x 1200 (WUXGA)'}, {'name': 'Powłoka matrycy', 'value': 'Matowa'},
    {'name': 'Rodzaj ekranu', 'value': 'Bez ekranu dotykowego'}, {'name': 'Typ matrycy', 'value': 'IPS'},
    {'name': 'Częstotliwość odświeżania', 'value': '165 Hz'}, {'name': 'Złącze HDMI', 'value': 'Pełnowymiarowe'},
    {'name': 'Złącze DisplayPort', 'value': 'Brak'}, {'name': 'Złącze D-Sub', 'value': 'Brak'},
    {'name': 'Złącza Audio', 'value': '1'}, {'name': 'Thunderbolt', 'value': 'Brak'}, {'name': 'USB 3.0', 'value': '2'},
    {'name': 'USB-C', 'value': '2'}, {'name': 'USB 2.0', 'value': 'Brak'},
    {'name': 'Czytnik kart pamięci', 'value': 'Nie'}, {'name': 'Karta sieciowa', 'value': '1 Gb/s'},
    {'name': 'Modem internetowy', 'value': 'Nie'}, {'name': 'WiFi', 'value': '802.11ax (gen. 6)'},
    {'name': 'Bluetooth', 'value': 'Bluetooth'}, {'name': 'Pojemność akumulatora', 'value': '73 Wh'},
    {'name': 'System operacyjny', 'value': 'Brak'}, {'name': 'Wersja językowa', 'value': 'Brak'},
    {'name': 'Dodatkowe urządzenia wskazujące', 'value': 'Brak'},
    {'name': 'Klawiatura', 'value': 'Pełnowymiarowa,\nWyspowa'}, {'name': 'Podświetlana klawiatura', 'value': 'Tak'},
    {'name': 'Kamera', 'value': 'Z kamerą'},
    {'name': 'Czytnik linii papilarnych', 'value': 'Bez czytnika linii papilarnych'},
    {'name': 'Rozpoznawanie twarzy', 'value': 'Nie'}, {'name': 'Szyfrowanie TPM', 'value': 'Tak'},
    {'name': 'Gniazdo linki zabezpieczającej', 'value': 'Tak'}, {'name': 'Wysokość [cm]', 'value': '2.89'},
    {'name': 'Szerokość [cm]', 'value': '36.1'}, {'name': 'Głębokość [cm]', 'value': '25.9'},
    {'name': 'Waga [kg]', 'value': '2.5'}]
products_details0 = [
    {'product_name': 'Laptop Gigabyte G6X 9KG 2024 i7-13650HX  / 16 GB / 1 TB / RTX 4060 / 165 Hz (9KG-43EE854SD)'},
    {'product_price': '4 299 zł'}, {
        'product_images': ['https://newsletter.morele.net/Gigabyte_Aorus_60EUR_Steam_1170x265_karta_produktu.png',
                           'https://images.morele.net/description/marketplace/7909c5aea9d0acd5b235c21341472c54.png',
                           'https://images.morele.net/description/marketplace/5c46fd6452ce9faefd48ae44b95c405d.png',
                           'https://images.morele.net/description/marketplace/da021fc9826ab2b142f0c384f3380c57.jpeg',
                           'https://images.morele.net/description/43/43c6477af49cfad400de25c44b2763eb.jpeg',
                           'https://images.morele.net/description/f3/f37e90c2ce9f7a608eeecacd271da1bb.jpeg']}, '4/5',
    {'product_average_rate': '4/5'}, {'name': 'Producent', 'value': 'Gigabyte'},
    {'name': 'Kod producenta', 'value': '9KG-43EE854SD'}, {'name': 'EAN', 'value': '4719331758417'},
    {'name': 'Typ', 'value': 'Laptop'}, {'name': 'Zastosowanie', 'value': 'Gamingowe'},
    {'name': 'Kolor', 'value': 'Czarne'}, {'name': 'Seria', 'value': 'Gigabyte G6'},
    {'name': 'Rodzina procesora', 'value': 'Intel Core i7'}, {'name': 'Procesor', 'value': 'Intel Core i7-13650HX'},
    {'name': 'Taktowanie procesora (bazowe/turbo)', 'value': '1.9 GHz / 4.9 GHz'},
    {'name': 'Liczba rdzeni / wątków', 'value': '14/20'}, {'name': 'Pamięć RAM (zainstalowana)', 'value': '16 GB'},
    {'name': 'Pamięć RAM (maksymalna)', 'value': '64 GB'}, {'name': 'Typ pamięci RAM', 'value': 'DDR5'},
    {'name': 'Częstotliwość pamięci', 'value': '4800 MHz'},
    {'name': 'Ilość gniazd pamięci (ogółem/wolne)', 'value': '2/0'}, {'name': 'Dysk HDD', 'value': 'Brak'},
    {'name': 'Dysk SSD', 'value': 'Brak'}, {'name': 'Dysk SSD M.2', 'value': 'Brak'},
    {'name': 'Dysk SSD M.2 PCIe', 'value': '1 TB'}, {'name': 'Napędy', 'value': 'Brak'},
    {'name': 'Zintegrowany układ graficzny', 'value': 'Intel UHD Graphics Xe'},
    {'name': 'Dedykowany układ graficzny', 'value': 'NVIDIA GeForce RTX 4060 Laptop GPU'},
    {'name': 'Pamięć karty graficznej', 'value': '8 GB'}, {'name': 'Typ pamięci', 'value': 'GDDR6'},
    {'name': 'MGP', 'value': '105 W'}, {'name': 'Przekątna ekranu', 'value': '16"'},
    {'name': 'Rozdzielczość', 'value': '1920 x 1200 (WUXGA)'}, {'name': 'Powłoka matrycy', 'value': 'Matowa'},
    {'name': 'Rodzaj ekranu', 'value': 'Bez ekranu dotykowego'}, {'name': 'Typ matrycy', 'value': 'IPS'},
    {'name': 'Częstotliwość odświeżania', 'value': '165 Hz'}, {'name': 'Złącze HDMI', 'value': 'Pełnowymiarowe'},
    {'name': 'Złącze DisplayPort', 'value': 'Brak'}, {'name': 'Złącze D-Sub', 'value': 'Brak'},
    {'name': 'Złącza Audio', 'value': '1'}, {'name': 'Thunderbolt', 'value': 'Brak'}, {'name': 'USB 3.0', 'value': '2'},
    {'name': 'USB-C', 'value': '2'}, {'name': 'USB 2.0', 'value': 'Brak'},
    {'name': 'Czytnik kart pamięci', 'value': 'Nie'}, {'name': 'Karta sieciowa', 'value': '1 Gb/s'},
    {'name': 'Modem internetowy', 'value': 'Nie'}, {'name': 'WiFi', 'value': '802.11ax (gen. 6)'},
    {'name': 'Bluetooth', 'value': 'Bluetooth'}, {'name': 'Pojemność akumulatora', 'value': '73 Wh'},
    {'name': 'System operacyjny', 'value': 'Brak'}, {'name': 'Wersja językowa', 'value': 'Brak'},
    {'name': 'Dodatkowe urządzenia wskazujące', 'value': 'Brak'},
    {'name': 'Klawiatura', 'value': 'Pełnowymiarowa,\nWyspowa'}, {'name': 'Podświetlana klawiatura', 'value': 'Tak'},
    {'name': 'Kamera', 'value': 'Z kamerą'},
    {'name': 'Czytnik linii papilarnych', 'value': 'Bez czytnika linii papilarnych'},
    {'name': 'Rozpoznawanie twarzy', 'value': 'Nie'}, {'name': 'Szyfrowanie TPM', 'value': 'Tak'},
    {'name': 'Gniazdo linki zabezpieczającej', 'value': 'Tak'}, {'name': 'Wysokość [cm]', 'value': '2.89'},
    {'name': 'Szerokość [cm]', 'value': '36.1'}, {'name': 'Głębokość [cm]', 'value': '25.9'},
    {'name': 'Waga [kg]', 'value': '2.5'}]

products_details0 = [
    {'product_name': 'Laptop Gigabyte G6X 9KG 2024 i7-13650HX  / 16 GB / 1 TB / RTX 4060 / 165 Hz (9KG-43EE854SD)'},
    {'product_price': '4 299 zł'}, {
        'product_images': ['https://newsletter.morele.net/Gigabyte_Aorus_60EUR_Steam_1170x265_karta_produktu.png',
                           'https://images.morele.net/description/marketplace/7909c5aea9d0acd5b235c21341472c54.png',
                           'https://images.morele.net/description/marketplace/5c46fd6452ce9faefd48ae44b95c405d.png',
                           'https://images.morele.net/description/marketplace/da021fc9826ab2b142f0c384f3380c57.jpeg',
                           'https://images.morele.net/description/43/43c6477af49cfad400de25c44b2763eb.jpeg',
                           'https://images.morele.net/description/f3/f37e90c2ce9f7a608eeecacd271da1bb.jpeg']}, '4/5',
    {'product_average_rate': '4/5'}, {'name': 'Producent', 'value': 'Gigabyte'},
    {'name': 'Kod producenta', 'value': '9KG-43EE854SD'}, {'name': 'EAN', 'value': '4719331758417'},
    {'name': 'Typ', 'value': 'Laptop'}, {'name': 'Zastosowanie', 'value': 'Gamingowe'},
    {'name': 'Kolor', 'value': 'Czarne'}, {'name': 'Seria', 'value': 'Gigabyte G6'},
    {'name': 'Rodzina procesora', 'value': 'Intel Core i7'}, {'name': 'Procesor', 'value': 'Intel Core i7-13650HX'},
    {'name': 'Taktowanie procesora (bazowe/turbo)', 'value': '1.9 GHz / 4.9 GHz'},
    {'name': 'Liczba rdzeni / wątków', 'value': '14/20'}, {'name': 'Pamięć RAM (zainstalowana)', 'value': '16 GB'},
    {'name': 'Pamięć RAM (maksymalna)', 'value': '64 GB'}, {'name': 'Typ pamięci RAM', 'value': 'DDR5'},
    {'name': 'Częstotliwość pamięci', 'value': '4800 MHz'},
    {'name': 'Ilość gniazd pamięci (ogółem/wolne)', 'value': '2/0'}, {'name': 'Dysk HDD', 'value': 'Brak'},
    {'name': 'Dysk SSD', 'value': 'Brak'}, {'name': 'Dysk SSD M.2', 'value': 'Brak'},
    {'name': 'Dysk SSD M.2 PCIe', 'value': '1 TB'}, {'name': 'Napędy', 'value': 'Brak'},
    {'name': 'Zintegrowany układ graficzny', 'value': 'Intel UHD Graphics Xe'},
    {'name': 'Dedykowany układ graficzny', 'value': 'NVIDIA GeForce RTX 4060 Laptop GPU'},
    {'name': 'Pamięć karty graficznej', 'value': '8 GB'}, {'name': 'Typ pamięci', 'value': 'GDDR6'},
    {'name': 'MGP', 'value': '105 W'}, {'name': 'Przekątna ekranu', 'value': '16"'},
    {'name': 'Rozdzielczość', 'value': '1920 x 1200 (WUXGA)'}, {'name': 'Powłoka matrycy', 'value': 'Matowa'},
    {'name': 'Rodzaj ekranu', 'value': 'Bez ekranu dotykowego'}, {'name': 'Typ matrycy', 'value': 'IPS'},
    {'name': 'Częstotliwość odświeżania', 'value': '165 Hz'}, {'name': 'Złącze HDMI', 'value': 'Pełnowymiarowe'},
    {'name': 'Złącze DisplayPort', 'value': 'Brak'}, {'name': 'Złącze D-Sub', 'value': 'Brak'},
    {'name': 'Złącza Audio', 'value': '1'}, {'name': 'Thunderbolt', 'value': 'Brak'}, {'name': 'USB 3.0', 'value': '2'},
    {'name': 'USB-C', 'value': '2'}, {'name': 'USB 2.0', 'value': 'Brak'},
    {'name': 'Czytnik kart pamięci', 'value': 'Nie'}, {'name': 'Karta sieciowa', 'value': '1 Gb/s'},
    {'name': 'Modem internetowy', 'value': 'Nie'}, {'name': 'WiFi', 'value': '802.11ax (gen. 6)'},
    {'name': 'Bluetooth', 'value': 'Bluetooth'}, {'name': 'Pojemność akumulatora', 'value': '73 Wh'},
    {'name': 'System operacyjny', 'value': 'Brak'}, {'name': 'Wersja językowa', 'value': 'Brak'},
    {'name': 'Dodatkowe urządzenia wskazujące', 'value': 'Brak'},
    {'name': 'Klawiatura', 'value': 'Pełnowymiarowa,\nWyspowa'}, {'name': 'Podświetlana klawiatura', 'value': 'Tak'},
    {'name': 'Kamera', 'value': 'Z kamerą'},
    {'name': 'Czytnik linii papilarnych', 'value': 'Bez czytnika linii papilarnych'},
    {'name': 'Rozpoznawanie twarzy', 'value': 'Nie'}, {'name': 'Szyfrowanie TPM', 'value': 'Tak'},
    {'name': 'Gniazdo linki zabezpieczającej', 'value': 'Tak'}, {'name': 'Wysokość [cm]', 'value': '2.89'},
    {'name': 'Szerokość [cm]', 'value': '36.1'}, {'name': 'Głębokość [cm]', 'value': '25.9'},
    {'name': 'Waga [kg]', 'value': '2.5'}]
products_details1 = [
    {'product_name': 'Laptop MSI Thin 15 B12UCX-1818XPL i5-12450H / 16 GB / 512 GB / RTX 2050 / 144 Hz'},
    {'product_price': '2 499 zł'}, {
        'product_images': ['https://newsletter.morele.net/MSI_NB_G2A_NEW_LAYOUT_KARTA_PRODUKTU.png',
                           'https://newsletter.morele.net/MSI_NB_Holiday_sale_2024_Karta_produktu.png',
                           'https://newsletter.morele.net/MSI_NB_War_Mongrels_intel_1170x265_karta_produktu.png',
                           'https://images.morele.net/description/b1/b1cdff300a92a23e457805c2ef06696b.jpeg',
                           'https://images.morele.net/description/0c/0cb53417f9cbfd7be6fd27e472483b75.png',
                           'https://images.morele.net/description/11/11381cf7490b2eedbbd8b6e9ef57ed53.jpeg',
                           'https://images.morele.net/description/76/767fb4746ae892e7fd5bcd99769f709a.jpeg']}, '0/5',
    {'product_average_rate': '0/5'}, {'name': 'Producent', 'value': 'MSI'},
    {'name': 'Kod producenta', 'value': 'B12UCX-1818XPL'}, {'name': 'EAN', 'value': '4711377199230'},
    {'name': 'Typ', 'value': 'Laptop'}, {'name': 'Zastosowanie', 'value': 'Gamingowe'},
    {'name': 'Kolor', 'value': 'Szare'}, {'name': 'Seria', 'value': 'MSI Thin'},
    {'name': 'Rodzina procesora', 'value': 'Intel Core i5'}, {'name': 'Procesor', 'value': 'Intel Core i5-12450H'},
    {'name': 'Taktowanie procesora (bazowe/turbo)', 'value': '1.5 GHz / 4.4 GHz'},
    {'name': 'Liczba rdzeni / wątków', 'value': '8/12'}, {'name': 'Pamięć RAM (zainstalowana)', 'value': '16 GB'},
    {'name': 'Pamięć RAM (maksymalna)', 'value': '64 GB'}, {'name': 'Typ pamięci RAM', 'value': 'DDR4'},
    {'name': 'Częstotliwość pamięci', 'value': '3200 MHz'},
    {'name': 'Ilość gniazd pamięci (ogółem/wolne)', 'value': '2/0'}, {'name': 'Dysk HDD', 'value': 'Brak'},
    {'name': 'Dysk SSD', 'value': 'Brak'}, {'name': 'Dysk SSD M.2', 'value': 'Brak'},
    {'name': 'Dysk SSD M.2 PCIe', 'value': '512 GB'}, {'name': 'Napędy', 'value': 'Brak'},
    {'name': 'Zintegrowany układ graficzny', 'value': 'Intel UHD Graphics Xe G4'},
    {'name': 'Dedykowany układ graficzny', 'value': 'NVIDIA GeForce RTX 2050'},
    {'name': 'Pamięć karty graficznej', 'value': '4 GB'}, {'name': 'Typ pamięci', 'value': 'GDDR6'},
    {'name': 'Przekątna ekranu', 'value': '15.6"'}, {'name': 'Rozdzielczość', 'value': '1920 x 1080 (Full HD)'},
    {'name': 'Powłoka matrycy', 'value': 'Matowa'}, {'name': 'Rodzaj ekranu', 'value': 'Bez ekranu dotykowego'},
    {'name': 'Typ matrycy', 'value': 'IPS'}, {'name': 'Częstotliwość odświeżania', 'value': '144 Hz'},
    {'name': 'Złącze HDMI', 'value': 'Pełnowymiarowe'}, {'name': 'Złącze DisplayPort', 'value': 'Brak'},
    {'name': 'Złącze D-Sub', 'value': 'Brak'}, {'name': 'Złącza Audio', 'value': 'Brak'},
    {'name': 'Thunderbolt', 'value': 'Brak'}, {'name': 'USB 3.0', 'value': '2'}, {'name': 'USB-C', 'value': '1'},
    {'name': 'USB 2.0', 'value': 'Brak'}, {'name': 'Czytnik kart pamięci', 'value': 'Nie'},
    {'name': 'Karta sieciowa', 'value': '1 Gb/s'}, {'name': 'Modem internetowy', 'value': 'Nie'},
    {'name': 'WiFi', 'value': '802.11ax (gen. 6)'}, {'name': 'Bluetooth', 'value': 'Bluetooth'},
    {'name': 'Pojemność akumulatora', 'value': '52.5 Wh'}, {'name': 'System operacyjny', 'value': 'Brak'},
    {'name': 'Wersja językowa', 'value': 'Brak'}, {'name': 'Dodatkowe urządzenia wskazujące', 'value': 'Brak'},
    {'name': 'Klawiatura', 'value': 'Wyspowa'}, {'name': 'Podświetlana klawiatura', 'value': 'Tak'},
    {'name': 'Kamera', 'value': 'Z kamerą'},
    {'name': 'Czytnik linii papilarnych', 'value': 'Bez czytnika linii papilarnych'},
    {'name': 'Rozpoznawanie twarzy', 'value': 'Nie'}, {'name': 'Szyfrowanie TPM', 'value': 'Tak'},
    {'name': 'Gniazdo linki zabezpieczającej', 'value': 'Tak'}, {'name': 'Wysokość [cm]', 'value': '21.7'},
    {'name': 'Szerokość [cm]', 'value': '35.9'}, {'name': 'Głębokość [cm]', 'value': '25.4'},
    {'name': 'Waga [kg]', 'value': '1.86'}]

products_details2 = [{
    'product_name': 'Laptop Gigabyte Aorus 16X 9KG 2024 i7-13650HX / 16 GB / 1 TB / RTX 4060 / 165 Hz (9KG-43EEC54SD)'},
    {'product_price': '4 998 zł'}, {'product_images': [
        'https://newsletter.morele.net/Gigabyte_Aorus_60EUR_Steam_1170x265_karta_produktu.png',
        'https://images.morele.net/description/e7/e7b9f5f9bdc4a28ec5c2211e3bb1959e.jpeg',
        'https://images.morele.net/description/c8/c895432a93cab05ed357085c5d9af5cc.png',
        'https://images.morele.net/description/cf/cf997d50c9940f4f05cc7fb1b878f6c5.png',
        'https://images.morele.net/description/bc/bc20b2fe601ef572279faaf5f353c80a.png',
        'https://images.morele.net/description/marketplace/15f8f76aa7b223bf87bd7b8f4a2dcb76.jpeg',
        'https://images.morele.net/description/20/2016c265f3206bc31c5907d72c2d187b.png']}, '5/5',
    {'product_average_rate': '5/5'}, {'name': 'Producent', 'value': 'Gigabyte'},
    {'name': 'Kod producenta', 'value': '9KG-43EEC54SD'}, {'name': 'EAN', 'value': '4719331761189'},
    {'name': 'Typ', 'value': 'Laptop'}, {'name': 'Zastosowanie', 'value': 'Gamingowe'},
    {'name': 'Kolor', 'value': 'Szare'}, {'name': 'Seria', 'value': 'Gigabyte Aorus'},
    {'name': 'Rodzina procesora', 'value': 'Intel Core i7'},
    {'name': 'Procesor', 'value': 'Intel Core i7-13650HX'},
    {'name': 'Taktowanie procesora (bazowe/turbo)', 'value': '1.9 GHz / 4.9 GHz'},
    {'name': 'Liczba rdzeni / wątków', 'value': '14/20'},
    {'name': 'Pamięć RAM (zainstalowana)', 'value': '16 GB'},
    {'name': 'Pamięć RAM (maksymalna)', 'value': '64 GB'},
    {'name': 'Typ pamięci RAM', 'value': 'DDR5'},
    {'name': 'Częstotliwość pamięci', 'value': '5600 MHz'},
    {'name': 'Ilość gniazd pamięci (ogółem/wolne)', 'value': '2/0'},
    {'name': 'Dysk HDD', 'value': 'Brak'}, {'name': 'Dysk SSD', 'value': 'Brak'},
    {'name': 'Dysk SSD M.2', 'value': 'Brak'}, {'name': 'Dysk SSD M.2 PCIe', 'value': '1 TB'},
    {'name': 'Napędy', 'value': 'Brak'},
    {'name': 'Zintegrowany układ graficzny', 'value': 'Intel UHD Graphics Xe'},
    {'name': 'Dedykowany układ graficzny', 'value': 'NVIDIA GeForce RTX 4060 Laptop GPU'},
    {'name': 'Pamięć karty graficznej', 'value': '8 GB'}, {'name': 'Typ pamięci', 'value': 'GDDR6'},
    {'name': 'MGP', 'value': '140 W'}, {'name': 'Przekątna ekranu', 'value': '16"'},
    {'name': 'Rozdzielczość', 'value': '2560 x 1600 (WQXGA)'},
    {'name': 'Powłoka matrycy', 'value': 'Matowa'},
    {'name': 'Rodzaj ekranu', 'value': 'Bez ekranu dotykowego'},
    {'name': 'Typ matrycy', 'value': 'IPS'}, {'name': 'Częstotliwość odświeżania', 'value': '165 Hz'},
    {'name': 'Złącze HDMI', 'value': 'Pełnowymiarowe'},
    {'name': 'Złącze DisplayPort', 'value': 'Brak'}, {'name': 'Złącze D-Sub', 'value': 'Brak'},
    {'name': 'Złącza Audio', 'value': '1'}, {'name': 'Thunderbolt', 'value': '1'},
    {'name': 'USB 3.0', 'value': '2'}, {'name': 'USB-C', 'value': '1'},
    {'name': 'USB 2.0', 'value': 'Brak'}, {'name': 'Czytnik kart pamięci', 'value': 'Tak'},
    {'name': 'Karta sieciowa', 'value': '1 Gb/s'}, {'name': 'Modem internetowy', 'value': 'Nie'},
    {'name': 'WiFi', 'value': '802.11be (gen. 7)'}, {'name': 'Bluetooth', 'value': 'Bluetooth'},
    {'name': 'Pojemność akumulatora', 'value': '99 Wh'},
    {'name': 'System operacyjny', 'value': 'Brak'}, {'name': 'Wersja językowa', 'value': 'Brak'},
    {'name': 'Dodatkowe urządzenia wskazujące', 'value': 'Brak'},
    {'name': 'Klawiatura', 'value': 'Wyspowa'}, {'name': 'Podświetlana klawiatura', 'value': 'Tak'},
    {'name': 'Kamera', 'value': 'Z kamerą'},
    {'name': 'Czytnik linii papilarnych', 'value': 'Bez czytnika linii papilarnych'},
    {'name': 'Rozpoznawanie twarzy', 'value': 'Tak'}, {'name': 'Szyfrowanie TPM', 'value': 'Nie'},
    {'name': 'Gniazdo linki zabezpieczającej', 'value': 'Nie'},
    {'name': 'Wysokość [cm]', 'value': '2.7'}, {'name': 'Szerokość [cm]', 'value': '35.6'},
    {'name': 'Głębokość [cm]', 'value': '25.4'}, {'name': 'Waga [kg]', 'value': '2.3'}]

products_details3 = [
    {'product_name': 'Laptop Lenovo Legion Pro 5 16IRX9 i5-14500HX / 32 GB / 1 TB / RTX 4060 / 240 Hz (83DF00EKPB)'},
    {'product_price': '6 394 zł'}, {
        'product_images': ['https://newsletter.morele.net/Lenovo_NB_box_1170x265_karta_produktu.png',
                           'https://newsletter.morele.net/Nvidia-karta-produktu-new.png',
                           'https://images.morele.net/description/9f/9f9865947576d3f716082e9ed071db09.jpeg',
                           'https://images.morele.net/description/8d/8d4111dcf22765124176a67006a880cb.jpeg',
                           'https://images.morele.net/description/62/626f8a33b99b84ca905504428945a9a2.jpeg',
                           'https://images.morele.net/description/92/92813b8094e35b0da46bd7bf6e59c397.jpeg',
                           'https://images.morele.net/description/1a/1a2a9e37a6751c11151f960ff717c3a3.jpeg',
                           'https://images.morele.net/description/c7/c7657caf1ecfaaf9382170db0ac68171.jpeg',
                           'https://images.morele.net/description/ef/efe9dec11dd390888651b58b175f91f8.jpeg',
                           'https://images.morele.net/description/d8/d8e40a3d1c6eb2e376bffdeaccde533b.jpeg',
                           'https://images.morele.net/description/4d/4d5dbc370afe68caa8e1f852aeff52fd.jpeg',
                           'https://images.morele.net/description/06/0616a2a479a4981dcba3f75b79488182.jpeg',
                           'https://images.morele.net/description/62/629f35232a2b4d8d69eed09330e2e740.jpeg']}, '5/5',
    {'product_average_rate': '5/5'}, {'name': 'Producent', 'value': 'Lenovo'},
    {'name': 'Kod producenta', 'value': '83DF00EKPB'}, {'name': 'EAN', 'value': ''}, {'name': 'Typ', 'value': 'Laptop'},
    {'name': 'Zastosowanie', 'value': 'Gamingowe'}, {'name': 'Kolor', 'value': 'Czarne'},
    {'name': 'Seria', 'value': 'Lenovo Legion Pro 5'}, {'name': 'Rodzina procesora', 'value': 'Intel Core i5'},
    {'name': 'Procesor', 'value': 'Intel Core i5-14500HX'},
    {'name': 'Taktowanie procesora (bazowe/turbo)', 'value': '1.8 GHz / 5 GHz'},
    {'name': 'Liczba rdzeni / wątków', 'value': '14/20'}, {'name': 'Pamięć RAM (zainstalowana)', 'value': '32 GB'},
    {'name': 'Pamięć RAM (maksymalna)', 'value': '64 GB'}, {'name': 'Typ pamięci RAM', 'value': 'DDR5'},
    {'name': 'Częstotliwość pamięci', 'value': '5600 MHz'},
    {'name': 'Ilość gniazd pamięci (ogółem/wolne)', 'value': '2/0'}, {'name': 'Dysk HDD', 'value': 'Brak'},
    {'name': 'Dysk SSD', 'value': 'Brak'}, {'name': 'Dysk SSD M.2', 'value': 'Brak'},
    {'name': 'Dysk SSD M.2 PCIe', 'value': '1 TB'}, {'name': 'Napędy', 'value': 'Brak'},
    {'name': 'Zintegrowany układ graficzny', 'value': 'Intel UHD Graphics 770'},
    {'name': 'Dedykowany układ graficzny', 'value': 'NVIDIA GeForce RTX 4060 Laptop GPU'},
    {'name': 'Pamięć karty graficznej', 'value': '8 GB'}, {'name': 'Typ pamięci', 'value': 'GDDR6'},
    {'name': 'MGP', 'value': '140 W'}, {'name': 'Przekątna ekranu', 'value': '16"'},
    {'name': 'Rozdzielczość', 'value': '2560 x 1600 (WQXGA)'}, {'name': 'Powłoka matrycy', 'value': 'Matowa'},
    {'name': 'Rodzaj ekranu', 'value': 'Bez ekranu dotykowego'}, {'name': 'Typ matrycy', 'value': 'IPS'},
    {'name': 'Częstotliwość odświeżania', 'value': '240 Hz'}, {'name': 'Złącze HDMI', 'value': 'Pełnowymiarowe'},
    {'name': 'Złącze DisplayPort', 'value': 'Brak'}, {'name': 'Złącze D-Sub', 'value': 'Brak'},
    {'name': 'Złącza Audio', 'value': '1'}, {'name': 'Thunderbolt', 'value': 'Brak'}, {'name': 'USB 3.0', 'value': '4'},
    {'name': 'USB-C', 'value': '2'}, {'name': 'USB 2.0', 'value': 'Brak'},
    {'name': 'Czytnik kart pamięci', 'value': 'Nie'}, {'name': 'Karta sieciowa', 'value': '1 Gb/s'},
    {'name': 'Modem internetowy', 'value': 'Nie'}, {'name': 'WiFi', 'value': '802.11ax (gen. 6)'},
    {'name': 'Bluetooth', 'value': 'Bluetooth'}, {'name': 'Pojemność akumulatora', 'value': '80 Wh'},
    {'name': 'System operacyjny', 'value': 'Brak'}, {'name': 'Wersja językowa', 'value': 'Brak'},
    {'name': 'Dodatkowe urządzenia wskazujące', 'value': 'Brak'},
    {'name': 'Klawiatura', 'value': 'Pełnowymiarowa,\nWyspowa'}, {'name': 'Podświetlana klawiatura', 'value': 'Tak'},
    {'name': 'Układ klawiatury', 'value': 'QWERTY polski programisty'}, {'name': 'Kamera', 'value': 'Z kamerą'},
    {'name': 'Czytnik linii papilarnych', 'value': 'Bez czytnika linii papilarnych'},
    {'name': 'Rozpoznawanie twarzy', 'value': 'Nie'}, {'name': 'Szyfrowanie TPM', 'value': 'Tak'},
    {'name': 'Gniazdo linki zabezpieczającej', 'value': 'Nie'}, {'name': 'Wysokość [cm]', 'value': '2.7'},
    {'name': 'Szerokość [cm]', 'value': '36.3'}, {'name': 'Głębokość [cm]', 'value': '26.2'},
    {'name': 'Waga [kg]', 'value': '2.5'}]

products_details4 = [{
    'product_name': 'Laptop Lenovo IdeaPad Gaming 3 15ACH6 Ryzen 5 5500H / 16 GB / 512 GB / RTX 2050 / 144 Hz (82K2028DPB)'},
    {'product_price': '2 399 zł'}, {'product_images': [
        'https://newsletter.morele.net/Lenovo_polski_gaming_1170x265_karta_produktu.png',
        'https://newsletter.morele.net/Lenovo_NB_box_1170x265_karta_produktu.png',
        'https://images.morele.net/description/33/33e837bbeeffd6bcd172d9e1cd4817cc.png']}, '4.5/5',
    {'product_average_rate': '4.5/5'}, {'name': 'Producent', 'value': 'Lenovo'},
    {'name': 'Kod producenta', 'value': '82K2028DPB'}, {'name': 'EAN', 'value': ''},
    {'name': 'Części modyfikowane', 'value': 'Pamięć do laptopa,\nSystem operacyjny'},
    {'name': 'Produkt modyfikowany przez sklep', 'value': 'Tak'}, {'name': 'Typ', 'value': 'Laptop'},
    {'name': 'Zastosowanie', 'value': 'Gamingowe'}, {'name': 'Kolor', 'value': 'Czarne'},
    {'name': 'Seria', 'value': 'Lenovo IdeaPad Gaming'},
    {'name': 'Rodzina procesora', 'value': 'AMD Ryzen'},
    {'name': 'Procesor', 'value': 'AMD Ryzen 5 5500H'},
    {'name': 'Taktowanie procesora (bazowe/turbo)', 'value': '3.3 GHz / 4.2 GHz'},
    {'name': 'Liczba rdzeni / wątków', 'value': '4/8'},
    {'name': 'Pamięć RAM (zainstalowana)', 'value': '16 GB'},
    {'name': 'Pamięć RAM (maksymalna)', 'value': '32 GB'},
    {'name': 'Typ pamięci RAM', 'value': 'DDR4'},
    {'name': 'Częstotliwość pamięci', 'value': '3200 MHz'},
    {'name': 'Ilość gniazd pamięci (ogółem/wolne)', 'value': '2/0'},
    {'name': 'Dysk HDD', 'value': 'Brak'}, {'name': 'Dysk SSD', 'value': 'Brak'},
    {'name': 'Dysk SSD M.2', 'value': 'Brak'}, {'name': 'Dysk SSD M.2 PCIe', 'value': '512 GB'},
    {'name': 'Napędy', 'value': 'Brak'},
    {'name': 'Zintegrowany układ graficzny', 'value': 'AMD Radeon RX Vega 7'},
    {'name': 'Dedykowany układ graficzny', 'value': 'NVIDIA GeForce RTX 2050'},
    {'name': 'Pamięć karty graficznej', 'value': '4 GB'}, {'name': 'Typ pamięci', 'value': 'GDDR6'},
    {'name': 'Przekątna ekranu', 'value': '15.6"'},
    {'name': 'Rozdzielczość', 'value': '1920 x 1080 (Full HD)'},
    {'name': 'Powłoka matrycy', 'value': 'Matowa'},
    {'name': 'Rodzaj ekranu', 'value': 'Bez ekranu dotykowego'},
    {'name': 'Typ matrycy', 'value': 'IPS'}, {'name': 'Częstotliwość odświeżania', 'value': '144 Hz'},
    {'name': 'Złącze HDMI', 'value': 'Pełnowymiarowe'},
    {'name': 'Złącze DisplayPort', 'value': 'Brak'}, {'name': 'Złącze D-Sub', 'value': 'Brak'},
    {'name': 'Złącza Audio', 'value': '1'}, {'name': 'Thunderbolt', 'value': 'Brak'},
    {'name': 'USB 3.0', 'value': '2'}, {'name': 'USB-C', 'value': '1'},
    {'name': 'USB 2.0', 'value': 'Brak'}, {'name': 'Czytnik kart pamięci', 'value': 'Nie'},
    {'name': 'Karta sieciowa', 'value': '1 Gb/s'}, {'name': 'Modem internetowy', 'value': 'Nie'},
    {'name': 'WiFi', 'value': '802.11ax (gen. 6)'}, {'name': 'Bluetooth', 'value': 'Bluetooth'},
    {'name': 'Pojemność akumulatora', 'value': '45 Wh'},
    {'name': 'System operacyjny', 'value': 'Brak'}, {'name': 'Wersja językowa', 'value': 'Brak'},
    {'name': 'Dodatkowe urządzenia wskazujące', 'value': 'Brak'},
    {'name': 'Klawiatura', 'value': 'Pełnowymiarowa,\nWyspowa'},
    {'name': 'Podświetlana klawiatura', 'value': 'Tak'}, {'name': 'Kamera', 'value': 'Z kamerą'},
    {'name': 'Czytnik linii papilarnych', 'value': 'Bez czytnika linii papilarnych'},
    {'name': 'Rozpoznawanie twarzy', 'value': 'Nie'}, {'name': 'Szyfrowanie TPM', 'value': 'Tak'},
    {'name': 'Gniazdo linki zabezpieczającej', 'value': 'Nie'},
    {'name': 'Wysokość [cm]', 'value': '2.42'}, {'name': 'Szerokość [cm]', 'value': '36'},
    {'name': 'Głębokość [cm]', 'value': '25.2'}, {'name': 'Waga [kg]', 'value': '2.25'}]

products_details5 = [
    {'product_name': 'Laptop Lenovo IdeaPad Slim 3 15IAH8 i5-12450H / 16 GB / 512 GB / W11 (83ER008MPB)'},
    {'product_price': '2 702,53 zł'}, {
        'product_images': ['https://newsletter.morele.net/Lenovo_NB_box_1170x265_karta_produktu.png',
                           'https://images.morele.net/description/13100000/13087394_2023_08_23_12_36_511567476826.jpeg',
                           'https://images.morele.net/description/13100000/13087394_2023_08_23_12_36_532074974299.jpeg',
                           'https://images.morele.net/description/13100000/13087394_2023_08_23_12_36_521866811926.jpeg',
                           'https://images.morele.net/description/13100000/13087394_2023_08_23_12_36_52795946204.jpeg']},
    '5/5', {'product_average_rate': '5/5'}, {'name': 'Producent', 'value': 'Lenovo'},
    {'name': 'Kod producenta', 'value': '83ER008MPB'}, {'name': 'EAN', 'value': ''}, {'name': 'Typ', 'value': 'Laptop'},
    {'name': 'Zastosowanie', 'value': 'Multimedialne'}, {'name': 'Kolor', 'value': 'Niebieskie'},
    {'name': 'Seria', 'value': 'Lenovo IdeaPad Slim'}, {'name': 'Rodzina procesora', 'value': 'Intel Core i5'},
    {'name': 'Procesor', 'value': 'Intel Core i5-12450H'},
    {'name': 'Taktowanie procesora (bazowe/turbo)', 'value': '1.5 GHz / 4.4 GHz'},
    {'name': 'Liczba rdzeni / wątków', 'value': '8/12'}, {'name': 'Pamięć RAM (zainstalowana)', 'value': '16 GB'},
    {'name': 'Pamięć RAM (maksymalna)', 'value': '16 GB'}, {'name': 'Typ pamięci RAM', 'value': 'DDR5L'},
    {'name': 'Częstotliwość pamięci', 'value': '4800 MHz'},
    {'name': 'Ilość gniazd pamięci (ogółem/wolne)', 'value': '0/0'}, {'name': 'Dysk HDD', 'value': 'Brak'},
    {'name': 'Dysk SSD', 'value': 'Brak'}, {'name': 'Dysk SSD M.2', 'value': 'Brak'},
    {'name': 'Dysk SSD M.2 PCIe', 'value': '512 GB'}, {'name': 'Napędy', 'value': 'Brak'},
    {'name': 'Zintegrowany układ graficzny', 'value': 'Intel UHD Graphics Xe'},
    {'name': 'Dedykowany układ graficzny', 'value': 'Brak'},
    {'name': 'Pamięć karty graficznej', 'value': 'Współdzielona z RAM'},
    {'name': 'Typ pamięci', 'value': 'Nie dotyczy'}, {'name': 'Przekątna ekranu', 'value': '15.6"'},
    {'name': 'Rozdzielczość', 'value': '1920 x 1080 (Full HD)'}, {'name': 'Powłoka matrycy', 'value': 'Matowa'},
    {'name': 'Rodzaj ekranu', 'value': 'Bez ekranu dotykowego'}, {'name': 'Typ matrycy', 'value': 'IPS'},
    {'name': 'Częstotliwość odświeżania', 'value': '60 Hz'}, {'name': 'Złącze HDMI', 'value': 'Pełnowymiarowe'},
    {'name': 'Złącze DisplayPort', 'value': 'Brak'}, {'name': 'Złącze D-Sub', 'value': 'Brak'},
    {'name': 'Złącza Audio', 'value': '1'}, {'name': 'Thunderbolt', 'value': 'Brak'}, {'name': 'USB 3.0', 'value': '2'},
    {'name': 'USB-C', 'value': '1'}, {'name': 'USB 2.0', 'value': 'Brak'},
    {'name': 'Czytnik kart pamięci', 'value': 'Tak'}, {'name': 'Karta sieciowa', 'value': 'Nie'},
    {'name': 'Modem internetowy', 'value': 'Nie'}, {'name': 'WiFi', 'value': '802.11ac (gen. 5)'},
    {'name': 'Bluetooth', 'value': 'Bluetooth'}, {'name': 'Pojemność akumulatora', 'value': '47 Wh'},
    {'name': 'System operacyjny', 'value': 'Windows 11 Home'}, {'name': 'Wersja językowa', 'value': 'polska'},
    {'name': 'Dodatkowe urządzenia wskazujące', 'value': 'Brak'},
    {'name': 'Klawiatura', 'value': 'Pełnowymiarowa,\nWyspowa'}, {'name': 'Podświetlana klawiatura', 'value': 'Nie'},
    {'name': 'Układ klawiatury', 'value': 'QWERTY polski programisty'}, {'name': 'Kamera', 'value': 'Z kamerą'},
    {'name': 'Czytnik linii papilarnych', 'value': 'Bez czytnika linii papilarnych'},
    {'name': 'Rozpoznawanie twarzy', 'value': 'Nie'}, {'name': 'Szyfrowanie TPM', 'value': 'Tak'},
    {'name': 'Gniazdo linki zabezpieczającej', 'value': 'Nie'}, {'name': 'Wysokość [cm]', 'value': '1.79'},
    {'name': 'Szerokość [cm]', 'value': '35.9'}, {'name': 'Głębokość [cm]', 'value': '23.5'},
    {'name': 'Waga [kg]', 'value': '1.62'}]

products_details6 = [
    {'product_name': 'Laptop Lenovo IdeaPad Slim 3 15ABR8 Ryzen 5 7430U / 16 GB / 512 GB / W11 (82XM00J0PB)'},
    {'product_price': '2 199 zł'}, {
        'product_images': ['https://newsletter.morele.net/Lenovo_NB_box_1170x265_karta_produktu.png',
                           'https://images.morele.net/description/57/57ca6a4eb07f127863393a850bba5407.jpeg',
                           'https://images.morele.net/description/c8/c843f13a01336cdb1e9ab08e308b43ae.jpeg',
                           'https://images.morele.net/description/00/007edefe8c12c74adaeb04d698a200aa.jpeg',
                           'https://images.morele.net/description/64/6452aa4c1b13494c8f74b5a604a1b052.jpeg']}, '5/5',
    {'product_average_rate': '5/5'}, {'name': 'Producent', 'value': 'Lenovo'},
    {'name': 'Kod producenta', 'value': '82XM00J0PB'}, {'name': 'EAN', 'value': ''}, {'name': 'Typ', 'value': 'Laptop'},
    {'name': 'Zastosowanie', 'value': 'Multimedialne'}, {'name': 'Kolor', 'value': 'Szare'},
    {'name': 'Seria', 'value': 'Lenovo IdeaPad Slim'}, {'name': 'Rodzina procesora', 'value': 'AMD Ryzen'},
    {'name': 'Procesor', 'value': 'AMD Ryzen 5 7430U'},
    {'name': 'Taktowanie procesora (bazowe/turbo)', 'value': '2.0 GHz / 4.5 GHz'},
    {'name': 'Liczba rdzeni / wątków', 'value': '6/12'}, {'name': 'Pamięć RAM (zainstalowana)', 'value': '16 GB'},
    {'name': 'Pamięć RAM (maksymalna)', 'value': '16 GB'}, {'name': 'Typ pamięci RAM', 'value': 'DDR4'},
    {'name': 'Częstotliwość pamięci', 'value': '3200 MHz'},
    {'name': 'Ilość gniazd pamięci (ogółem/wolne)', 'value': '0/0'}, {'name': 'Dysk HDD', 'value': 'Brak'},
    {'name': 'Dysk SSD', 'value': 'Brak'}, {'name': 'Dysk SSD M.2', 'value': 'Brak'},
    {'name': 'Dysk SSD M.2 PCIe', 'value': '512 GB'}, {'name': 'Napędy', 'value': 'Brak'},
    {'name': 'Zintegrowany układ graficzny', 'value': 'AMD Radeon RX Vega 7'},
    {'name': 'Dedykowany układ graficzny', 'value': 'Brak'},
    {'name': 'Pamięć karty graficznej', 'value': 'Współdzielona z RAM'},
    {'name': 'Typ pamięci', 'value': 'Nie dotyczy'}, {'name': 'Przekątna ekranu', 'value': '15.6"'},
    {'name': 'Rozdzielczość', 'value': '1920 x 1080 (Full HD)'}, {'name': 'Powłoka matrycy', 'value': 'Matowa'},
    {'name': 'Rodzaj ekranu', 'value': 'Bez ekranu dotykowego'}, {'name': 'Typ matrycy', 'value': 'IPS'},
    {'name': 'Częstotliwość odświeżania', 'value': '60 Hz'}, {'name': 'Złącze HDMI', 'value': 'Pełnowymiarowe'},
    {'name': 'Złącze DisplayPort', 'value': 'Brak'}, {'name': 'Złącze D-Sub', 'value': 'Brak'},
    {'name': 'Złącza Audio', 'value': '1'}, {'name': 'Thunderbolt', 'value': 'Brak'}, {'name': 'USB 3.0', 'value': '2'},
    {'name': 'USB-C', 'value': '1'}, {'name': 'USB 2.0', 'value': 'Brak'},
    {'name': 'Czytnik kart pamięci', 'value': 'Tak'}, {'name': 'Karta sieciowa', 'value': 'Nie'},
    {'name': 'Modem internetowy', 'value': 'Nie'}, {'name': 'WiFi', 'value': '802.11ax (gen. 6)'},
    {'name': 'Bluetooth', 'value': 'Bluetooth'}, {'name': 'Pojemność akumulatora', 'value': '47 Wh'},
    {'name': 'System operacyjny', 'value': 'Windows 11 Home'}, {'name': 'Wersja językowa', 'value': 'polska'},
    {'name': 'Dodatkowe urządzenia wskazujące', 'value': 'Brak'},
    {'name': 'Klawiatura', 'value': 'Pełnowymiarowa,\nWyspowa'}, {'name': 'Podświetlana klawiatura', 'value': 'Tak'},
    {'name': 'Kamera', 'value': 'Z kamerą'},
    {'name': 'Czytnik linii papilarnych', 'value': 'Bez czytnika linii papilarnych'},
    {'name': 'Rozpoznawanie twarzy', 'value': 'Nie'}, {'name': 'Szyfrowanie TPM', 'value': 'Tak'},
    {'name': 'Gniazdo linki zabezpieczającej', 'value': 'Nie'}, {'name': 'Wysokość [cm]', 'value': '1.79'},
    {'name': 'Szerokość [cm]', 'value': '35.9'}, {'name': 'Głębokość [cm]', 'value': '23.5'},
    {'name': 'Waga [kg]', 'value': '1.62'}]
products_details7 = [{'product_name': 'Laptop Dell Inspiron 3520 i5-1235U / 16 GB / 1 TB / W11 / 120 Hz (3520-2109)'},
                     {'product_price': '2 449 zł'}, {'product_images': [
        'https://images.morele.net/description/1e/1eefe0bc6bdb36c09fcaf970eeb905ff.png',
        'https://images.morele.net/description/9e/9ef0096fdfc6c8b55547cdc4234779a5.jpeg',
        'https://images.morele.net/description/13/130c64f2aa15c70cc3ec3112dcdcb37c.png',
        'https://images.morele.net/description/43/430405360fa9871c1860fa63033acc0e.png']}, '0/5',
                     {'product_average_rate': '0/5'}, {'name': 'Producent', 'value': 'Dell'},
                     {'name': 'Kod producenta', 'value': '3520-2109'}, {'name': 'EAN', 'value': '5397184942109'},
                     {'name': 'Typ', 'value': 'Laptop'}, {'name': 'Zastosowanie', 'value': 'Multimedialne'},
                     {'name': 'Kolor', 'value': 'Srebrne'}, {'name': 'Seria', 'value': 'Dell Inspiron'},
                     {'name': 'Rodzina procesora', 'value': 'Intel Core i5'},
                     {'name': 'Procesor', 'value': 'Intel Core i5-1235U'},
                     {'name': 'Taktowanie procesora (bazowe/turbo)', 'value': '0.9 GHz / 4.4 GHz'},
                     {'name': 'Liczba rdzeni / wątków', 'value': '10/12'},
                     {'name': 'Pamięć RAM (zainstalowana)', 'value': '16 GB'},
                     {'name': 'Pamięć RAM (maksymalna)', 'value': '32 GB'},
                     {'name': 'Typ pamięci RAM', 'value': 'DDR4'},
                     {'name': 'Częstotliwość pamięci', 'value': '3200 MHz'},
                     {'name': 'Ilość gniazd pamięci (ogółem/wolne)', 'value': '2/0'},
                     {'name': 'Dysk HDD', 'value': 'Brak'}, {'name': 'Dysk SSD', 'value': 'Brak'},
                     {'name': 'Dysk SSD M.2', 'value': 'Brak'}, {'name': 'Dysk SSD M.2 PCIe', 'value': '1 TB'},
                     {'name': 'Napędy', 'value': 'Brak'},
                     {'name': 'Zintegrowany układ graficzny', 'value': 'Intel Iris Xe'},
                     {'name': 'Dedykowany układ graficzny', 'value': 'Brak'},
                     {'name': 'Pamięć karty graficznej', 'value': 'Współdzielona z RAM'},
                     {'name': 'Typ pamięci', 'value': 'Nie dotyczy'}, {'name': 'Przekątna ekranu', 'value': '15.6"'},
                     {'name': 'Rozdzielczość', 'value': '1920 x 1080 (Full HD)'},
                     {'name': 'Powłoka matrycy', 'value': 'Matowa'},
                     {'name': 'Rodzaj ekranu', 'value': 'Bez ekranu dotykowego'},
                     {'name': 'Typ matrycy', 'value': 'IPS'}, {'name': 'Częstotliwość odświeżania', 'value': '120 Hz'},
                     {'name': 'Złącze HDMI', 'value': 'Pełnowymiarowe'},
                     {'name': 'Złącze DisplayPort', 'value': 'Brak'}, {'name': 'Złącze D-Sub', 'value': 'Brak'},
                     {'name': 'Złącza Audio', 'value': '1'}, {'name': 'Thunderbolt', 'value': 'Brak'},
                     {'name': 'USB 3.0', 'value': '2'}, {'name': 'USB-C', 'value': 'Brak'},
                     {'name': 'USB 2.0', 'value': '1'}, {'name': 'Czytnik kart pamięci', 'value': 'Tak'},
                     {'name': 'Karta sieciowa', 'value': 'Nie'}, {'name': 'Modem internetowy', 'value': 'Nie'},
                     {'name': 'WiFi', 'value': '802.11ax (gen. 6)'}, {'name': 'Bluetooth', 'value': 'Bluetooth'},
                     {'name': 'Pojemność akumulatora', 'value': '54 Wh'},
                     {'name': 'System operacyjny', 'value': 'Windows 11 Home'},
                     {'name': 'Wersja językowa', 'value': 'polska'},
                     {'name': 'Dodatkowe urządzenia wskazujące', 'value': 'Brak'},
                     {'name': 'Klawiatura', 'value': 'Pełnowymiarowa,\nWyspowa'},
                     {'name': 'Podświetlana klawiatura', 'value': 'Nie'}, {'name': 'Kamera', 'value': 'Z kamerą'},
                     {'name': 'Czytnik linii papilarnych', 'value': 'Bez czytnika linii papilarnych'},
                     {'name': 'Rozpoznawanie twarzy', 'value': 'Nie'}, {'name': 'Szyfrowanie TPM', 'value': 'Tak'},
                     {'name': 'Gniazdo linki zabezpieczającej', 'value': 'Nie'},
                     {'name': 'Wysokość [cm]', 'value': '1.98'}, {'name': 'Szerokość [cm]', 'value': '35.9'},
                     {'name': 'Głębokość [cm]', 'value': '23.5'}, {'name': 'Waga [kg]', 'value': '1.67'}]
products_details8 = [{'product_name': 'Laptop Lenovo IdeaPad 3 17IAU7 i5-1235U / 8 GB / 512 GB / W11 (82RL009UPB)'},
                     {'product_price': '2 299 zł'}, {
                         'product_images': ['https://newsletter.morele.net/Lenovo_NB_box_1170x265_karta_produktu.png',
                                            'https://images.morele.net/description/marketplace/ad586d6d693f631865ca69c024c0e6f1.jpeg',
                                            'https://images.morele.net/description/marketplace/a266484c98e15bc57ff69442a0a76d84.jpeg',
                                            'https://images.morele.net/description/marketplace/2f89bd12b42a04491d0b2f03b0daf9ce.jpeg',
                                            'https://images.morele.net/description/marketplace/f47bafd49bdb9ed71e4435682422e483.jpeg']},
                     '0/5', {'product_average_rate': '0/5'}, {'name': 'Producent', 'value': 'Lenovo'},
                     {'name': 'Kod producenta', 'value': '82RL009UPB'}, {'name': 'EAN', 'value': ''},
                     {'name': 'Typ', 'value': 'Laptop'}, {'name': 'Zastosowanie', 'value': 'Multimedialne'},
                     {'name': 'Kolor', 'value': 'Granatowe'}, {'name': 'Seria', 'value': 'Lenovo IdeaPad 3'},
                     {'name': 'Rodzina procesora', 'value': 'Intel Core i5'},
                     {'name': 'Procesor', 'value': 'Intel Core i5-1235U'},
                     {'name': 'Taktowanie procesora (bazowe/turbo)', 'value': '1.3 GHz / 4.4 GHz'},
                     {'name': 'Liczba rdzeni / wątków', 'value': '10/12'},
                     {'name': 'Pamięć RAM (zainstalowana)', 'value': '8 GB'},
                     {'name': 'Pamięć RAM (maksymalna)', 'value': '16 GB'},
                     {'name': 'Typ pamięci RAM', 'value': 'DDR4'},
                     {'name': 'Częstotliwość pamięci', 'value': '3200 MHz'},
                     {'name': 'Ilość gniazd pamięci (ogółem/wolne)', 'value': '2/1'},
                     {'name': 'Dysk HDD', 'value': 'Brak'}, {'name': 'Dysk SSD', 'value': 'Brak'},
                     {'name': 'Dysk SSD M.2', 'value': 'Brak'}, {'name': 'Dysk SSD M.2 PCIe', 'value': '512 GB'},
                     {'name': 'Napędy', 'value': 'Brak'},
                     {'name': 'Zintegrowany układ graficzny', 'value': 'Intel Iris Xe'},
                     {'name': 'Dedykowany układ graficzny', 'value': 'Brak'},
                     {'name': 'Pamięć karty graficznej', 'value': 'Współdzielona z RAM'},
                     {'name': 'Typ pamięci', 'value': 'Nie dotyczy'}, {'name': 'Przekątna ekranu', 'value': '17.3"'},
                     {'name': 'Rozdzielczość', 'value': '1920 x 1080 (Full HD)'},
                     {'name': 'Powłoka matrycy', 'value': 'Matowa'},
                     {'name': 'Rodzaj ekranu', 'value': 'Bez ekranu dotykowego'},
                     {'name': 'Typ matrycy', 'value': 'IPS'}, {'name': 'Częstotliwość odświeżania', 'value': '60 Hz'},
                     {'name': 'Złącze HDMI', 'value': 'Pełnowymiarowe'},
                     {'name': 'Złącze DisplayPort', 'value': 'Brak'}, {'name': 'Złącze D-Sub', 'value': 'Brak'},
                     {'name': 'Złącza Audio', 'value': '1'}, {'name': 'Thunderbolt', 'value': 'Brak'},
                     {'name': 'USB 3.0', 'value': '1'}, {'name': 'USB-C', 'value': '1'},
                     {'name': 'USB 2.0', 'value': '1'}, {'name': 'Czytnik kart pamięci', 'value': 'Tak'},
                     {'name': 'Karta sieciowa', 'value': 'Nie'}, {'name': 'Modem internetowy', 'value': 'Nie'},
                     {'name': 'WiFi', 'value': '802.11ac (gen. 5)'}, {'name': 'Bluetooth', 'value': 'Bluetooth'},
                     {'name': 'Pojemność akumulatora', 'value': '38 Wh'},
                     {'name': 'System operacyjny', 'value': 'Windows 11 Home'},
                     {'name': 'Wersja językowa', 'value': 'polska'},
                     {'name': 'Dodatkowe urządzenia wskazujące', 'value': 'Brak'},
                     {'name': 'Klawiatura', 'value': 'Pełnowymiarowa,\nWyspowa'},
                     {'name': 'Podświetlana klawiatura', 'value': 'Nie'},
                     {'name': 'Układ klawiatury', 'value': 'QWERTY polski programisty'},
                     {'name': 'Kamera', 'value': 'Z kamerą'},
                     {'name': 'Czytnik linii papilarnych', 'value': 'Bez czytnika linii papilarnych'},
                     {'name': 'Rozpoznawanie twarzy', 'value': 'Nie'}, {'name': 'Szyfrowanie TPM', 'value': 'Tak'},
                     {'name': 'Gniazdo linki zabezpieczającej', 'value': 'Nie'},
                     {'name': 'Wysokość [cm]', 'value': '1.99'}, {'name': 'Szerokość [cm]', 'value': '39.9'},
                     {'name': 'Głębokość [cm]', 'value': '27.4'}, {'name': 'Waga [kg]', 'value': '2.04'}]
products_details9 = [
    {'product_name': 'Laptop Lenovo LOQ 15ARP9 Ryzen 5 7235HS / 16 GB / 512 GB / RTX 3050 / 144 Hz (83JC0068PB)'},
    {'product_price': '2 999 zł'}, {
        'product_images': ['https://newsletter.morele.net/Lenovo_NB_box_1170x265_karta_produktu.png',
                           'https://images.morele.net/description/59/5923f8ef975f2099d1ab86036eb2ada0.jpeg', '',
                           'https://images.morele.net/description/c7/c7b52726254645c5f1b51d14f93a924f.jpeg',
                           'https://images.morele.net/description/21/21d5b793b7315e51ed7385f2dcf15624.jpeg',
                           'https://images.morele.net/description/f9/f961721fc198d6454decaddc5d56a860.jpeg',
                           'https://images.morele.net/description/71/7150c532e793ad08d4f0f7f9ccc5379e.png']}, '4/5',
    {'product_average_rate': '4/5'}, {'name': 'Producent', 'value': 'Lenovo'},
    {'name': 'Kod producenta', 'value': '83JC0068PB'}, {'name': 'EAN', 'value': ''}, {'name': 'Typ', 'value': 'Laptop'},
    {'name': 'Zastosowanie', 'value': 'Gamingowe'}, {'name': 'Kolor', 'value': 'Szare'},
    {'name': 'Seria', 'value': 'Lenovo LOQ'}, {'name': 'Rodzina procesora', 'value': 'AMD Ryzen'},
    {'name': 'Procesor', 'value': 'AMD Ryzen 5 7235HS'},
    {'name': 'Taktowanie procesora (bazowe/turbo)', 'value': '3.1 GHz / 4.5 GHz'},
    {'name': 'Liczba rdzeni / wątków', 'value': '4/8'}, {'name': 'Pamięć RAM (zainstalowana)', 'value': '16 GB'},
    {'name': 'Pamięć RAM (maksymalna)', 'value': '64 GB'}, {'name': 'Typ pamięci RAM', 'value': 'DDR5'},
    {'name': 'Częstotliwość pamięci', 'value': '4800 MHz'},
    {'name': 'Ilość gniazd pamięci (ogółem/wolne)', 'value': '2/0'}, {'name': 'Dysk HDD', 'value': 'Brak'},
    {'name': 'Dysk SSD', 'value': 'Brak'}, {'name': 'Dysk SSD M.2', 'value': 'Brak'},
    {'name': 'Dysk SSD M.2 PCIe', 'value': '512 GB'}, {'name': 'Napędy', 'value': 'Brak'},
    {'name': 'Zintegrowany układ graficzny', 'value': 'Brak'},
    {'name': 'Dedykowany układ graficzny', 'value': 'NVIDIA GeForce RTX 3050 Laptop GPU'},
    {'name': 'Pamięć karty graficznej', 'value': '6 GB'}, {'name': 'Typ pamięci', 'value': 'GDDR6'},
    {'name': 'MGP', 'value': '95 W'}, {'name': 'Przekątna ekranu', 'value': '15.6"'},
    {'name': 'Rozdzielczość', 'value': '1920 x 1080 (Full HD)'}, {'name': 'Powłoka matrycy', 'value': 'Matowa'},
    {'name': 'Rodzaj ekranu', 'value': 'Bez ekranu dotykowego'}, {'name': 'Typ matrycy', 'value': 'IPS'},
    {'name': 'Częstotliwość odświeżania', 'value': '144 Hz'}, {'name': 'Złącze HDMI', 'value': 'Pełnowymiarowe'},
    {'name': 'Złącze DisplayPort', 'value': 'Brak'}, {'name': 'Złącze D-Sub', 'value': 'Brak'},
    {'name': 'Złącza Audio', 'value': '1'}, {'name': 'Thunderbolt', 'value': 'Brak'}, {'name': 'USB 3.0', 'value': '3'},
    {'name': 'USB-C', 'value': '1'}, {'name': 'USB 2.0', 'value': 'Brak'},
    {'name': 'Czytnik kart pamięci', 'value': 'Nie'}, {'name': 'Karta sieciowa', 'value': '1 Gb/s'},
    {'name': 'Modem internetowy', 'value': 'Nie'}, {'name': 'WiFi', 'value': '802.11ax (gen. 6)'},
    {'name': 'Bluetooth', 'value': 'Bluetooth'}, {'name': 'Pojemność akumulatora', 'value': '60 Wh'},
    {'name': 'System operacyjny', 'value': 'Brak'}, {'name': 'Wersja językowa', 'value': 'Brak'},
    {'name': 'Dodatkowe urządzenia wskazujące', 'value': 'Brak'},
    {'name': 'Klawiatura', 'value': 'Pełnowymiarowa,\nWyspowa'}, {'name': 'Podświetlana klawiatura', 'value': 'Tak'},
    {'name': 'Układ klawiatury', 'value': 'QWERTY polski programisty'}, {'name': 'Kamera', 'value': 'Z kamerą'},
    {'name': 'Czytnik linii papilarnych', 'value': 'Bez czytnika linii papilarnych'},
    {'name': 'Rozpoznawanie twarzy', 'value': 'Nie'}, {'name': 'Szyfrowanie TPM', 'value': 'Tak'},
    {'name': 'Gniazdo linki zabezpieczającej', 'value': 'Nie'}, {'name': 'Wysokość [cm]', 'value': '2.39'},
    {'name': 'Szerokość [cm]', 'value': '36'}, {'name': 'Głębokość [cm]', 'value': '25.9'},
    {'name': 'Waga [kg]', 'value': '2.38'}]
